### PR TITLE
CCE: Create mock PCMM interface

### PR DESCRIPTION
**Pull request by taylorrassmannlibertyits**
Set up mock endpoints for PCMM data with three different example returns.
https://vajira.max.gov/browse/API-5306

### CODE REVIEW

**Review by as-va — COMMENTED** [review]
Looks good. One quick question before approval: do we know if `Active` and `Pending` (and no data) are the only assignment status responses we can get? I checked the ICD but it does not specify the values for this field other than to say it is a string.

**Comment by taylorrassmannlibertyits** [comment]
> Looks good. One quick question before approval: do we know if `Active` and `Pending` (and no data) are the only assignment status responses we can get? I checked the ICD but it does not specify the values for this field other than to say it is a string.

There are two other results `Inactive` and `Cancelled` as well.

**Review by jnguy-va — APPROVED** [review]
New mock endpoints returning as expected.
Old CCE calls unchanged.

**Review by as-va — APPROVED** [review]
Confirmed with PCMM that `Inactive` and `Cancelled` states are internal states only. The only states the API will return are `Active`, `Pending`, and `No Data` which are covered by this PR.

**Pull request merged**
